version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/store-1-production
    overwrite: yes
permissions:
  - object: /home/ubuntu/store-1-production
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: deploy/scripts/after.sh
      timeout: 1800
      runas: ubuntu
