version: '3.8'
services:
  web:
    image: nginx:latest
    volumes:
      - ./deploy/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client/build:/usr/share/nginx/html
    depends_on:
      - app
    ports:
      - '80:80'

  app:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile
    depends_on:
      - db
    environment:
      TZ: 'Asia/Seoul'
    working_dir: /app
    networks:
      default:
        aliases:
          - app

  db:
    image: mysql:8.0.26
    environment:
      MYSQL_DATABASE: 'store'
      MYSQL_USER: 'woowa'
      MYSQL_PASSWORD: 'woowa'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      TZ: 'Asia/Seoul'
    cap_add:
      - SYS_NICE
    volumes:
      - ./deploy/data/mysql:/var/lib/mysql
    ports:
      - '33061:3306'
    networks:
      default:
        aliases:
          - db
