version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 14
    volumes:
      - ../../:/workspace/store-1
    command: sleep infinity
    network_mode: service:db
  db:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
