version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 14
    depends_on:
      - db
    volumes:
      - ../../:/workspace/store-1:cached
    command: sleep infinity
    network_mode: service:db
    environment:
      TZ: 'Asia/Seoul'
  db:
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql:cached
    environment:
      MYSQL_DATABASE: 'store'
      MYSQL_USER: 'woowa'
      MYSQL_PASSWORD: 'woowa'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      TZ: 'Asia/Seoul'
    networks:
      default:
        aliases:
          - db
  elasticsearch:
    build:
      context: ../elk/elasticsearch/
      args:
        ELK_VERSION: 7.14.0
    volumes:
      - type: bind
        source: ../elk/elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: '-Xmx256m -Xms256m'
      discovery.type: single-node
      TZ: 'Asia/Seoul'
    networks:
      default:
  kibana:
    build:
      context: ../elk/kibana/
      args:
        ELK_VERSION: 7.14.0
    volumes:
      - type: bind
        source: ../elk/kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    environment:
      TZ: 'Asia/Seoul'
    networks:
      default:
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
  logstash:
    build:
      context: ../elk/logstash/
      args:
        ELK_VERSION: 7.14.0
    links:
      - 'elasticsearch'
    volumes:
      - type: bind
        source: ../elk/logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ../elk/logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    environment:
      LS_JAVA_OPTS: '-Xmx256m -Xms256m'
      TZ: 'Asia/Seoul'
    networks:
      default:
    depends_on:
      - elasticsearch
      - db

volumes:
  elasticsearch:
